sudo: required

services:
  - docker

env:
  global:
    - IMAGE_NAME=darkn3bula/rocknroll
    - DOCKERFILE_PATH=Dockerfile.production

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - docker build -t $IMAGE_NAME:latest -f $DOCKERFILE_PATH .
  - docker push $IMAGE_NAME:latest
