
GET https://3000-darkn3bula2-gitcontaine-qsz2q4nvk0n.ws-us108.gitpod.io/api/ HTTP/1.1
Accept: */*
Content-Type: application/json
x-api-key: haGv9z3ZNTwBfHBszfOjeu8q3ZfARGcN

###

// User CRUD

POST  https://3000-darkn3bula2-gitcontaine-qsz2q4nvk0n.ws-us108.gitpod.io/api/users/register HTTP/1.1
Accept: */* 
Content-Type: application/json
x-api-key: haGv9z3ZNTwBfHBszfOjeu8q3ZfARGcN

  {
    "username": "fazal22",
    "email": "fazal@admin.hps.com",
    "name": "Khawaja Fazal Ur Rehman",
    "father_name": "Khawaja Abdul Rasheed Rathore",
    "gender": "male",
    "cnic": "34603-6721888-7",
    "dob": "1974-11-22",
    "cnic_issued_date": "2021-03-02",
    "cnic_expiry_date": "2031-03-02",
    "password": "temp1234"
  }

###

GET  https://3000-darkn3bula2-gitcontaine-qsz2q4nvk0n.ws-us108.gitpod.io/api/users HTTP/1.1
Accept: */*
Content-Type: application/json
x-api-key: haGv9z3ZNTwBfHBszfOjeu8q3ZfARGcN


### Login

POST  https://3000-darkn3bula2-gitcontaine-qsz2q4nvk0n.ws-us108.gitpod.io/api/users/login HTTP/1.1
Accept: */*
Content-Type: application/json
x-api-key: haGv9z3ZNTwBfHBszfOjeu8q3ZfARGcN

{
    "email": "fazal@admin.hps.com",
    "password": "temp1234"
}

