export enum SubjectNames {
    English = 'English',
    English_A = 'English_A',
    English_B = 'English_B',
    Urdu = 'Urdu',
    Urdu_A = 'Urdu_A',
    Urdu_B = 'Urdu_B',
    Math = 'Math',
    Gen_Math = 'Gen_Math',
    Science = 'Science',
    Gen_Science = 'Gen_Science',
    Drawing = 'Drawing',
    Nazra_Quran = 'Nazra_Quran',
    Islamiyat = 'Islamiyat',
    Islamiyat_Com = 'Islamiyat_Com',
    Social_Studies = 'Social_Studies',
    Computer = 'Computer',
    History_Geo = 'History_Geo',
    Tarjama_tul_Quran = 'Tarjama_tul_Quran',
    Islamic_Studies = 'Islamic_Studies',
    Pak_Studies = 'Pak_Studies',
    Chemistry = 'Chemistry',
    Physics = 'Physics',
    Biology = 'Biology'
}
