name: Copy Deployment Files to Shadow Folder

on:
  push:
    branches:
      - cidi

jobs:
  copy-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add SSH host key to known_hosts
        run: |
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" >> $HOME/.ssh/known_hosts
      - name: Copy files to shadow directory
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./src root@24.199.76.209:/var/www/app/git-container_shadow/
          scp -o StrictHostKeyChecking=no ./docker-compose.yaml root@24.199.76.209:/var/www/app/git-container_shadow/
          scp -o StrictHostKeyChecking=no ./package.json root@24.199.76.209:/var/www/app/git-container_shadow/

        shell: bash
      
