name: Deploy to DigitalOcean

on:
  push:
    branches:
      - deploy  # Your deployment branch

jobs:
  deployment:
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}


    - name: Copy repository to DigitalOcean
      run: |
        rsync -avz -e "ssh -o StrictHostKeyChecking=no" --exclude='.git*' --delete ./ ${{ secrets.DIGITALOCEAN_USER }}@${{ secrets.DIGITALOCEAN_IP }}:/path/to/your/application/temp_deploy/
      shell: bash

    - name: Check contents on the Droplet
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.DIGITALOCEAN_USER }}@${{ secrets.DIGITALOCEAN_IP }} "ls -al /path/to/your/application/temp_deploy/"
