name: Deploy to DigitalOcean

on:
  push:
    branches:
      - deploy  # Your deployment branch

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2


    - name: Add SSH key to known_hosts
      run: |
        ssh-keyscan -t rsa ${{ secrets.DIGITALOCEAN_IP }} >> ~/.ssh/known_hosts

    - name: Copy repository to DigitalOcean
      run: |
        rsync -avz --exclude='.git*' --delete ./ ${{ secrets.DIGITALOCEAN_USER }}@${{ secrets.DIGITALOCEAN_IP }}:/var/www/dropts/temp_deploy/
      shell: bash

    - name: Check contents on the Droplet
      run: |
        ssh ${{ secrets.DIGITALOCEAN_USER }}@${{ secrets.DIGITALOCEAN_IP }} "ls -al /var/www/dropts/temp_deploy/"
