name: Deploy Application

on:
  push:
    branches:
      - cidi

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy project files
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" --exclude '/node_modules' --exclude '/test' ./ root@24.199.76.209:/var/www/app/git-container/
        shell: bash

      - name: Redeploy application
        run: |
          ssh -o StrictHostKeyChecking=no root@24.199.76.209 << EOF
            cd /var/www/app/git-container/
            docker-compose down
            docker-compose up --build -d
          EOF
        shell: bash
