name: Docker Flow

on:
  push:
    branches:
      - cidi  # Set this to your deployment branch, if different

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: myapp/myapp:${{ github.sha }},myapp/myapp:latest
       

    
      -
        name: save image SHA
        run: echo "SHA=${{ github.sha }}" >> $GITHUB_ENV