# name: Check and copy files to Hostinger

# on:
#   push:
#     branches:
#       - main

# jobs:
#   test-ssh:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Setup SSH key
#         run: |
#           mkdir -p ~/.ssh
#           echo "${{ secrets.HOSTINGER_DEPLOY_KEY }}" > ~/.ssh/deploy_key
#           chmod 600 ~/.ssh/deploy_key
#           ls -la ~/.ssh/deploy_key

#       - name: Debug key format
#         run: |
#           head -n 1 ~/.ssh/deploy_key
#           echo "Key length (should be >100):"
#           wc -l ~/.ssh/deploy_key

#       - name: Add known hosts
#         run: |
#           echo "${{ secrets.HOSTINGER_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts

#       - name: Test connection
#         run: |
#           ssh -v -i ~/.ssh/deploy_key ${{ secrets.HOSTINGER_USER }}@${{ secrets.HOSTINGER_IP }} "echo 'Connected!'"

#       - name: Deploy with rsync
#         run: |
#           rsync -avz -e "ssh -o StrictHostKeyChecking=no" \
#             --exclude '.git*' \
#             --exclude 'node_modules' \
#             --exclude 'test' \
#             --exclude '.env' \
#             --exclude 'logs' \
#             --exclude 'dist' \
#             ./ ${{ secrets.HOSTINGER_USER }}@${{ secrets.HOSTINGER_IP }}:/var/www/hps/


name: Check and copy files to Hostinger

on:
  push:
    branches:
      - version/hostinger

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.HOSTINGER_DEPLOY_KEY }}
          known_hosts: ${{ secrets.HOSTINGER_KNOWN_HOSTS }}
          if_key_exists: replace

      - name: Test SSH Connection
        run: |
          ssh -v -o StrictHostKeyChecking=no ${{ secrets.HOSTINGER_USER }}@${{ secrets.HOSTINGER_IP }} "echo 'Connection test successful'"

      - name: Check destination directory permissions
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.HOSTINGER_USER }}@${{ secrets.HOSTINGER_IP }} '
            ls -la /var/www/
            mkdir -p /var/www/hps
            chmod 755 /var/www/hps
          '

      - name: Deploy with rsync (verbose)
        run: |
          eval $(ssh-agent -s)
          ssh-add - <<< "${{ secrets.HOSTINGER_DEPLOY_KEY }}"
          rsync -avvz --progress -e "ssh -v -o StrictHostKeyChecking=no" \
            --exclude '.git*' \
            --exclude 'node_modules' \
            --exclude 'test' \
            --exclude '.env' \
            --exclude 'logs' \
            --exclude 'dist' \
            ./ ${{ secrets.HOSTINGER_USER }}@${{ secrets.HOSTINGER_IP }}:/var/www/hps/

      - name: Verify files
        if: success()
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.HOSTINGER_USER }}@${{ secrets.HOSTINGER_IP }} '
            ls -la /var/www/hps/
          '
