name: Push Change Workflow

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup SSH
              uses: webfactory/ssh-agent@v0.5.3
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

            - name: Copy project files
              run: |
                  rsync -avz -e "ssh -o StrictHostKeyChecking=no" --exclude '/node_modules' --exclude '/test' ./ root@24.199.76.209:/var/www/app/git-container/
              shell: bash

            - name: Cleanup and Rebuild
              run: |
                  ssh -o StrictHostKeyChecking=no root@24.199.76.209 << EOF
                    cd /var/www/app/git-container/
                    docker-compose down
                    # docker system prune -af
                    # Verbose build with debugging
                    DOCKER_BUILDKIT=0 docker-compose build --progress=plain
                    docker-compose up -d
                  EOF
              shell: bash

            - name: Wait for Nginx to Start
              run: |
                  echo "Waiting for Nginx container to start..."
                  sleep 10
              shell: bash

            - name: Reload Nginx
              run: |
                  ssh -o StrictHostKeyChecking=no root@24.199.76.209 << EOF
                    echo "Reloading Nginx to apply new configuration..."
                    docker exec nginx nginx -s reload
                  EOF
              shell: bash
