name: Re-Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy project files
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" --exclude '/node_modules' --exclude '/test' ./ root@24.199.76.209:/var/www/app/git-container/
        shell: bash

      - name: Redeploy application
        run: |
          ssh -o StrictHostKeyChecking=no root@24.199.76.209 << EOF
            set -e

            cd /var/www/app/git-container/

            # Stop and remove any running containers and networks
            docker-compose down || true

            # Build or rebuild the Docker images and start the containers
            docker-compose up --build -d

            # Check if the containers are running
            RUNNING_CONTAINERS=$(docker ps --filter "status=running" --format "{{.Names}}" | grep -v "^$")
            if [ -z "$RUNNING_CONTAINERS" ]; then
              echo "Error: No containers are running after deployment"
              exit 1
            else
              echo "Containers running: $RUNNING_CONTAINERS"
            fi
          EOF
        shell: bash

      - name: Handle deployment failure
        if: ${{ failure() }}
        run: |
          echo "Deployment failed. Please check the logs for more information."
          exit 1
