name: Test SSH Connection

on:
  push:
    branches:
      - cidi

jobs:
  test-ssh:
    runs-on: ubuntu-latest
    steps:
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Test SSH Connection
      run: ssh -o StrictHostKeyChecking=no root@146.190.1.163 echo "SSH connection successful"